apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web
        image: promalertsacr.azurecr.io/web:v1.0.40
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: BLA
          value: blabla
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: node
spec:
  #type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: web
---   
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webin
  namespace: node
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: "/"
spec:
  rules:
  - http:
      paths:
      - path: /blabladev
        pathType: Exact
        backend:
          service:
            name: web
            port: 
              number: 80
      - path: /metrics
        pathType: Exact
        backend:
          service:
            name: web
            port: 
              number: 80
          
