version: "3.1"
services:
  # web:
  #   build: .
  #   environment:
  #     - BLA=bla
  #   container_name: web
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./app/public:/usr/app/public
  #     - ./app/alerts:/usr/app/alerts
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: --log.level=debug --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
  # alertmanager:
  #   image: prom/alertmanager:latest
  #   container_name: alertmanager
  #   ports:
  #     - 9093:9093
  #   command: --log.level=debug --config.file=/etc/prometheus/alertmanager.yml
  #   volumes:
  #     - ./alertmanager.yml:/etc/prometheus/alertmanager.yml
