version: "3.1"
services:
  web:
    build: ./app
    environment:
      - BLA=bla
    container_name: web
    ports:
      - 3000:3000
    volumes:
      - ./app/public:/usr/app/public
      - ./app/alerts:/usr/app/alerts
    depends_on:
      - prometheus
  client:
    build: ./client
    environment:
      - BLA=bla
    container_name: client
    ports:
      - 4000:4000
    depends_on:
      - web
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: --log.level=debug --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
    external: true
