groups:
- name: blanoam
  rules:
  - record: noam_recorderd_metric
    expr: avg by (method) (rate(http_server_requests_seconds_count[1m]))

  - alert: demoBiggerThan8
    expr: noam_demo_metric > 8
    for: 2m
    labels:
      severity: page
    # Prometheus templates apply here in the annotation and label fields of the alert.
    annotations:
      description: 'instance: {{ $labels.instance }}, job {{ $labels.job }}. current value: {{ $value }}, city {{ $labels.city}}'
      summary: 'Metric is above 8' 